---
title: "Introduction_to_SolveSylvester"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction_to_SolveSylvester}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse = TRUE,
  comment = "#>"
)
library(SolSyl)
library(Matrix)
library(knitr)
```

```{r}
#A B are square Matrices and dimension of A is larger
A <- matrix(c(1,0,-1,2,1,0,0,0,-1),3,3,byrow = TRUE) #3x3 Matrix
B <- matrix(c(2,1,0,0),2,2,byrow = TRUE) #2x2 Matrix
C <- matrix(c(2,2,1,1,1,1),3,2) #3x2 Matrix
SolveSylvester(A,B,C)
```

```{r}
#A B are square Matrices and dimensions of A and B are the same
A <- matrix(c(1,0,-1,2,1,0,0,0,-1),3,3,byrow = TRUE) #3x3 Matrix
B <- matrix(c(2,1,0,0,1,3,4,5,0),3,3,byrow = TRUE) #3x3 Matrix
C <- matrix(c(2,2,1,1,1,1,3,2,4),3,3) #3x3 Matrix
SolveSylvester(A,B,C)
```

```{r}
#A B are square Matrices and dimension of B is larger
A <- matrix(c(1,0,-1,2),2,2,byrow = TRUE) #2x2 Matrix
B <- matrix(c(2,1,0,0,1,3,4,5,0),3,3,byrow = TRUE) #3x3 Matrix
C <- matrix(c(2,2,1,3,2,4),2,3) #2x3 Matrix
SolveSylvester(A,B,C)
```

```{r}
#A B are square Matrices and dimension of B is larger
A <- matrix(c(1,0,-1,2),2,2,byrow = TRUE) #2x2 Matrix
B <- matrix(c(2,1,0,0,1,3,4,5,0),3,3,byrow = TRUE) #3x3 Matrix
C <- matrix(c(2,2,1,3,2,4),2,3) #2x3 Matrix
X <- SolveSylvester(A,B,C)
```

```{r}
#A B are square Matrices and dimension of B is larger
A <- matrix(c(1,0,-1,2),2,2,byrow = TRUE) #2x2 Matrix
B <- 2 #number
C <- matrix(c(2,2,1,3),2,2) #2x2 Matrix
SolveSylvester(A,B,C)
```

```{r}
#A B are square Matrices and dimension of B is larger
A <- 2 #number
B <- matrix(c(1,0,-1,2),2,2,byrow = TRUE) #2x2 Matrix
C <- matrix(c(2,2,1,3),2,2) #2x2 Matrix
SolveSylvester(A,B,C)
```
